---
title: "R Shiny Beer App"
author: "Adeel Qureshi"
date: "2/6/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}

library(shiny)
library(dplyr)
library(shinyWidgets)
library(ggplot2)

beers = read.csv("/Users/adeel/Desktop/Data Science/Doing Data Science/Homework/Unit 8 and 9 Case Study 1/Beers.csv", header = TRUE)
breweries = read.csv("/Users/adeel/Desktop/Data Science/Doing Data Science/Homework/Unit 8 and 9 Case Study 1/Breweries.csv", header = TRUE)

beers <- beers %>% rename(Beer_Name = Name)
breweries <- breweries %>% rename(Brewery_Name = Name)
beerbrew <- merge(beers,breweries, by.x = "Brewery_id", by.y = "Brew_ID")
beerbrew$State <- trimws(beerbrew$State)

ui <- fluidPage(
  
  # App title ----
  titlePanel("Beer Data Case Study"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      #Copy the line below to make a select box 
       selectInput("parameter", label = h1("Selection"), 
                    choices = list("IBU" = "IBU", "ABV" = "ABV"), 
                    selected = 1),
                    hr(),
                    fluidRow(column(3, verbatimTextOutput("parameter"))),
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      # Output: Histogram ----
      plotOutput(outputId = "distPlot"),
    )
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output) {
  
  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$distPlot <- renderPlot({
    
  if(input$parameter == "IBU")
  {
      x <- beerbrew %>% filter(!is.na(IBU))
      x <- as.vector(x$IBU)
      bins <- seq(min(x), max(x), length.out = 20)
  
    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "IBU content per beer",
         main = "BEER Case Study Analysis of IBU")
  }
   if(input$parameter == "ABV")
  {
      x <- beerbrew %>% filter(!is.na(ABV))
      x <- as.vector(x$ABV)
      bins <- seq(min(x), max(x), length.out = 20)
  
    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "ABV content per beer",
         main = "BEER Case Study Analysis of ABV")
   }
  })
  
}


shinyApp(ui, server)
```
